name = "LBThieves Season 2"
author = "Dandandooo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58de9c97c7922a29947d8e6e1d994db8755c21100aa783b7d7a5fc5e9addcd85"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
